### Handling Inbalanced Dataset

1. Up Sampling 
2. Down Sampling

In [ ]:
import numpy as np
import pandas as pd

In [5]:
# set the random seed for reproducibility 
np.random.seed(123)

# Create a dataframe with two classes 

n_samples=1000
class_0_ratio=0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1=n_samples - n_class_0

In [6]:
n_class_0,n_class_1

(900, 100)

In [ ]:
### Create my dataframe with imbalanced dataset 

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2': np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] * n_class_0   ## 900 0 will be create in this dataframe
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2': np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1   ## 100 1 wil be created in ths dataframe
})

In [22]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [23]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [24]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [27]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## up sampling

In [ ]:
## upsampling 
## in this increase the number of 100 t0 900


df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [32]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\udemy\complete-python-bootcamp-main\10-data analysis with python\venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in d:\udemy\complete-python-bootcamp-main\10-data analysis with python\venv\lib\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in d:\udemy\complete-python-bootcamp-main\10-data analysis with python\venv\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in d:\udemy\complete-python-bootcamp-main\10-data analysis with python\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\udemy\complete-python-bootcamp-main\10-data analysis with python\venv\lib\site-packages (from scikit-learn) (3.6.0)

In [33]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True,   ## sample with replacement 
        n_samples=len(df_majority),                        ## increase till the length of majority
        random_state=42)

In [34]:
df_minority_upsampled.shape

(900, 3)

In [36]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [37]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [40]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down sampling

In [42]:
import numpy as np
import pandas as pd

# set the random seed for reproducibility 
np.random.seed(123)

# Create a dataframe with two classes 

n_samples=1000
class_0_ratio=0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1=n_samples - n_class_0

n_class_0,n_class_1


### Create my dataframe with imbalanced dataset 

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2': np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0] * n_class_0   ## 900 0 will be create in this dataframe
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2': np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1   ## 100 1 wil be created in ths dataframe
})


df=pd.concat([class_0,class_1]).reset_index(drop=True)

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [45]:
## Downsampling 
## in this it will remove the number of data


df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=True,
        n_samples=len(df_minority),
        random_state=42
        )

In [46]:
df_majority_downsampled.shape

(100, 3)

In [47]:
df_majority_downsampled.head()

     feature_1  feature_2  target
102   0.712265   0.718151       0
435   1.199988   0.574621       0
860   0.304515  -0.759475       0
270  -1.213385   0.675504       0
106   0.179549  -0.202659       0

In [50]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [51]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64